name: rust-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: test
        run: make rust-test
      - name: make wasm
        run: rustup target add wasm32-unknown-unknown && make wasm
      - name: archive wasm build
        uses: actions/upload-artifact@v3
        with:
          name: wasm-build
          path: static/cedar.wasm